//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_CRUD_ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies_table
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Release_date { get; set; }
        public string Movie_genre { get; set; }
    }
}
